#!/bin/bash
export DISPLAY_NUMBER=2
source "$HOME/.config/sketchybar/utils.sh"

LAYOUTS="$HOME/.config/sketchybar/layouts"
CONFIG_DIR="$HOME/.config/sketchybar"

# Determines if a monitor is used
# Since the notch is -only- on the laptop, if a monitor isn't used,
# then that means the internal display is used ¯\_(ツ)_/¯

if [ "$MONITOR_INTERNAL" = true ]; then
	source "$LAYOUTS/laptop-rounded.sh"
else
	source "$LAYOUTS/desktop-rounded.sh"
fi