#!/bin/bash

# PINK MIDDLE BAR
COLOR_A=$COLOR_DRACULA_BUFFY
COLOR_B=0xffa53e8f

COLOR_UTILS_BG=$COLOR_B
COLOR_SPACE_SELECTED_SPACE_NO_BG=$COLOR_A
COLOR_SPACE_SELECTED_BG=$COLOR_DRACULA_TEXT_DARK_BG
COLOR_SPACE_SELECTED_ICON=$COLOR_B

COLOR_SPOTIFY_BG=$COLOR_B