#!/bin/bash
export DISPLAY_NUMBER=1
LAYOUTS="$HOME/.config/sketchybar/layouts"

source "$HOME/.config/$BAR_NAME/utils.sh"

# Determines if a monitor is used
# Since the notch is -only- on the laptop, if a monitor isn't used,
# then that means the internal display is used ¯\_(ツ)_/¯

if [ "$MONITOR_INTERNAL" = true ]; then
	source "$LAYOUTS/laptop-rounded.sh"
else
	source "$LAYOUTS/desktop-rounded.sh"
fi