#!/bin/bash

# MAGENTA MIDDLE BAR
COLOR_A=0xff8aadf5
COLOR_B=0xff4a5d84

COLOR_UTILS_BG=$COLOR_B
COLOR_SPACE_SELECTED_SPACE_NO_BG=$COLOR_A
COLOR_SPACE_SELECTED_BG=$COLOR_DRACULA_TEXT_DARK_BG
COLOR_SPACE_SELECTED_ICON=$COLOR_B

COLOR_SPOTIFY_BG=$COLOR_B
